### ISSUE TITLE
Yearly and Monthly account balances don't seem to make sense

### ISSUE THREAD

**Issue by xentac** [aumayr/beancount-web#113]
If I click on any account and look at the yearly or monthly balances, it shows me numbers that seem to represent the change in the account.  What I'd really like is the absolute balance of the account in yearly or monthly blocks (probably on the last day of the block).  Then I can look at a particular account and be happy or sad that its absolute value is trending upwards or downwards.

**Comment by aumayr** [comment]
What the yearly and monthly balances do is calculate the balances for transactions in the corresponding year/month, and not represent a "running" balance and just display the intermediate balances at the end of the year/month.

**Comment by aumayr** [comment]
@xentac But if you want to change the behaviour it should be fairly trivial. Enabling this behaviour via a config-setting could be a good way to keep both versions. PRs welcome :-)

**Comment by xentac** [comment]
In the case where you're trading commodities it makes even less sense, it looks like I gained or lost USD when I'm really trading a commodity.

I'll see about writing some patches, but I'll have to wait till I get approval to release those patches from my company...

**Comment by corani** [comment]
I kind of agree with @xentac, the term `balance` seems to imply a running balance, not a change. I'm wondering if it would make more sense to rename these tabs to something like `Yearly/Monthly changes`  and add `Yearly/Monthly balances` tabs that show a running balance.

Both views are useful to me, I'd rather not hide either behind a config-setting.

**Comment by aumayr** [comment]
OK I see the point now, and like @corani's suggestion (adding both variants as separate "tabs"). I can provide the UI-adaptions (the tabs have to be visually updated if there are more than 2-3) if you want to implement this in the API, @xentac or @corani.

**Comment by aumayr** [comment]
The mentioned UI-adaptions (the Journal filters now wrap correctly): a296ed8

**Comment by xentac** [comment]
Pull request sent: https://github.com/aumayr/beancount-web/pull/119

**Comment by aumayr** [comment]
Merged - thanks all!
