### ISSUE TITLE
Feature Request: Uncollapse account tree one level at a time

### ISSUE THREAD

**Issue by davidastephens** [aumayr/beancount-web#116]
Is it possible to set up the uncollapse of the account tree to uncollapse one level at a time?  That way if I collapse the whole thing, I can drill into specific levels (sometime I want to see the aggregation).

Happy to work on a PR if you could point me to the file that would control this (html/css is not my speciality).

**Comment by aumayr** [comment]
Sounds like a helpful feature!

I have to think about if this should be the default-behavior. What about accessing this feature not by clicking on the uncollapse-rectangle, but `ctrl`-clicking?

**Comment by davidastephens** [comment]
That could work.  Personally I think it should be the default and ctrl clicking uncollapse all.

**Comment by aumayr** [comment]
Maybe toggle the behavior in the settings? 

Some pointers for a PR: 

- This should be relatively easy to implement, just modify the JavaScript-function that does the expanding/collapsing: https://github.com/aumayr/beancount-web/blob/master/beancount_web/static/javascript/main.js#L47-L58
- For keyboard-related features: [Mousetrap.js](https://craig.is/killing/mice) is already included (a JavaScript-library for handling keyboard shortcuts), used eg. here: https://github.com/aumayr/beancount-web/blob/master/beancount_web/static/javascript/main.js#L104-L117

**Comment by aumayr** [comment]
OK I think you are right - this should be the default behavior (but, again, a setting to toggle this behavior would be nice).

**Comment by davidastephens** [comment]
ok, I got it working on my machine.  I think I would prefer if the default level was 2 and I could drill down further as needed.  What do you think about a setting that controls the default level of detail?

**Comment by aumayr** [comment]
Can you send a PR so I can test it and see how it works?

**Comment by davidastephens** [comment]
PR sent - #118

**Comment by aumayr** [comment]
Looks good!

Are you going to add the "ctrl-click"-feature as well?

**Comment by davidastephens** [comment]
I wonder if we should use ctrl-click or just have a button called expand-all?

**Comment by aumayr** [comment]
Both:

- ctrl-click for expanding all sub-accounts for the current node
- In the table header, we could change "Accounts" to "Accounts (expand all)" (with "(expand all)" in a lighter color) and make that expand all nodes. The "(expand all)" could be hidden if everything is expanded (the default), and shown as soon as a node is collapsed.
- A tooltip on each node for hinting at the "ctrl-click"-thing (easy: the `title=""`-attribute of the triangles)

**Comment by davidastephens** [comment]
ok, I'll take a crack at those.

**Comment by davidastephens** [comment]
I added a "Accounts (collapse all)" that collapses everything then changes to "Accounts (expand all)".

Haven't figured out ctrl-click.  Does mousetrap have that functionality? It seems like it is only for keyboard commands (not combinations)?

**Comment by aumayr** [comment]
Merged PR #118 and added small changes in cc663a498421e11070b320ef7b1a288fa654515c

**Comment by redstreet** [comment]
Did the collapse behavior change recently? It seemed to work nicely in the past, but now, this is what I see. I'm opening up the balance sheet and clicking on the expander of Assets:

- initially, the entire hierarchy is expanded
- if I collapse, then expand, the entire hierarchy is expanded (previously, it would only expand the first level)
- if I want to see only the first level, what I need to do seems to be a bit non-intuitive:
  - **doesn't work**: collapse, then expand
  - **doesn't work**: collapse, then shift+expand
  - **works**: shift-collapse, then expand

Am I using this correctly?

**Comment by yagebu** [comment]
Yes the account tree was reimplemented in #246. I wasn't really aware of the discussion here, but collapsing with a single click should be a self-inverse operation, after expanding it should just show the same tree that you just collapsed.

I find the behaviour now much more consistent as both a single click and shirt-click will have matching behaviour for collapsing and expanding. As a shortcut for expanding just the first level, we could add ctrl-click, as was suggested above.

**Comment by redstreet** [comment]
> I find the behaviour now much more consistent as both a single click and shift-click will have matching behaviour for collapsing and expanding. 

The single-click behavior is indeed consistent, but I'm having trouble understanding the consistency in the shift-click behavior:

- single-click: collapse-all or expand-all (works fine, and is intuitive)

- shift-click: if I simply shift-click again and again, it behaves exactly the same as single-click (i.e., toggles between collapse-all and expand-all). however, if i shift-collapse, and then single-click-expand, it expands a single-level. I'm not understanding this behavior?

**Comment by yagebu** [comment]
> single-click: collapse-all or expand-all (works fine, and is intuitive)

Not "collapse all", just "collapse". It won't collapse any children-accounts (so you some children were collapsed, they'll still be if you expand again)

> shift-click: if I simply shift-click again and again, it behaves exactly the same as single-click (i.e., toggles between collapse-all and expand-all). However, if I shift-collapse, and then single-click-expand, it expands a single-level. I'm not understanding this behavior?

Shift-click is "collapse all recursively" and "expand all recursively". So to only show the first level, you first collapse the root and all its children recursively, and if you then expand the root, its children will still be collapsed.

**Comment by yagebu** [comment]
I believe that click-behaviour should behave as it does now. Not sure we really need shift-click actually (we also have the expand-all text that shows up in the table header)

**Comment by redstreet** [comment]
Okay, now it all makes sense, and is intuitive as well, thanks for explaining!

> I believe that click-behaviour should behave as it does now. Not sure we really need shift-click actually

Hmm, is there an alternative to "collapse all recursively" and "expand all recursively" ? If not, the shift-click is very useful and important.

> (we also have the expand-all text that shows up in the table header)

Not sure what you mean by this. Are you talking about the ````Hold the Shift-key while clicking to expand all children```` balloon help?
