### ISSUE TITLE
Change Year filter to allow for date ranges

### ISSUE THREAD

**Issue by aumayr** [aumayr/beancount-web#25]
Currently the filter only shows (and filters for) full years. Change that to enable arbitrary date ranges.

**Comment by yagebu** [comment]
I have implemented this in a branch and can submit a PR.

**Comment by aumayr** [comment]
@yagebu Perfect, thanks! I just pushed some changes to the filters, so be sure to check them out before you create a PR.

**Comment by aumayr** [comment]
Implemented in #27
