### ISSUE TITLE
Handle daterange-filter-strings that cannot be parsed successfully

### ISSUE THREAD

**Issue by aumayr** [aumayr/beancount-web#31]
When the user enters a daterange-filter-string that cannot be parsed successfully an error-message (or something like that) should be shown.

- [ ] Correct handling in `api.py`
- [ ] UI changes

**Comment by yagebu** [comment]
I will work on this. I guess I should at least fix the features I implemented :D

**Comment by aumayr** [comment]
Already fixed.
