### ISSUE TITLE
Global option to render numbers in their absolute value

### ISSUE THREAD

**Issue by aumayr** [aumayr/beancount-web#33]
@blais (from the Mailing list):

> Given how "pro" this looks, you may consider adding a global option to render the numbers in their absolute value, that is, negate the income, equity and liabilities numbers everywhere. I've been considering adding this to Beancount myself (both for input syntax and output reports actually), wondering if I could find a way to do that in a way you could reuse. This would make the presention easier to follow for "real" accountants by removing the surprising signs.

**Comment by aumayr** [comment]
Should this be handled in ´api.py´ (so the frontend does not know about it)?

**Comment by blais** [comment]
Not sure. I think I'll want to do the same in beancount/reports in eventually for those; if you're reusing that code, then it would make more sense for me to do it on that side. If not, then not.

**Comment by aumayr** [comment]
I looked into this and the right place for this setting is `beancount`. To honor this in all `api.py`-functions or to implement this in the templates of `beancount-web` itself would not be feasible.

**Comment by nkirsch** [comment]
@blais Are you tracking this issue elsewhere? I'm happy to take a crack at it if you want to give me some basic guidance on what in `beancount` needs to be changed. Thanks!
