### ISSUE TITLE
Render Journal entries asynchronously and with sensible defaults

### ISSUE THREAD

**Issue by aumayr** [aumayr/beancount-web#34]
Right now all the data for Journal entries is stored in the HTML of the page, and rendered as full, before filtering the already rendered HTML-elements via JavaScript. Additionally, legs are shown by default, which is what many users do not want.

- [ ] Request Journal entries data via AJAX (non-blocking the UI)
- [ ] Only render the Journal entry types selected by the user (filter)
- [ ] Only render legs if requested (default: not shown)

--- 
Historical background from on the Mailing list:

@blais (and others):
> I've been meaning to remove the rendering of postings in journals, to make them collapsible (and collapsed by default) like you did, but to only fetch the detail from the server when expanding a particular transaction or hovering over a particular link. This would have two advantages: (1) the journals would render much faster, by avoiding rendering all of these postings details by default, which is slow, and which is really an overkill amount of detail for the most part, and (2) the journals would look smaller on-screen and be much easier to read.

**Comment by aumayr** [comment]
@blais I implemented that and it speeds up the rendering of a Journal dramatically!

**Comment by blais** [comment]
Glad to hear!
