### ISSUE TITLE
Tables overlap on narrow screens / responsive design

### ISSUE THREAD

**Issue by corani** [aumayr/beancount-web#39]
This happens both on my phone (below) and on my computer. Ideally, if the screen is not wide enough, the tables on the right should be put below the ones on the left.

![screenshot_20151215-161027](https://cloud.githubusercontent.com/assets/480775/11805608/29cdc372-a348-11e5-9764-9d63096d4f76.png)

**Comment by aumayr** [comment]
@corani How narrow are we talking (in px)?

**Comment by corani** [comment]
In the case of my phone, 1440px wide, my laptop approx. 1200px available space. On my external screen (~1850px available) it shows correctly.

Some experimentation shows that if the window gets below ~1235px on my computer, tables begin to overlap.

**Comment by aumayr** [comment]
@corani I kind of fixed this by setting the minimum width to `1235px`. Can you try out if this works for you on your laptop and phone?

**Comment by corani** [comment]
Yes, works for both now, awesome!

**Comment by xentac** [comment]
I have two default currencies and this doesn't work all that well on my phone.

Would you be supportive to pull requests for actual responsive style (@media and all that).  Or even better, is there some responsive framework you'd prefer to use instead of writing all the CSS by hand?

**Comment by aumayr** [comment]
@xentac fava isn't optimized for a phone in any way. 

> Would you be supportive to pull requests for actual responsive style (@media and all that). Or even better, is there some responsive framework you'd prefer to use instead of writing all the CSS by hand?

Of course - help is always appreciated 🙂 Just open a PR and we can discuss the changes there.

I'm somewhat in favor of writhing all (S)CSS by hand, as it's not too complicated, and without any "side-effects" produced by the CSS-frameworks.
