### ISSUE TITLE
Enable filtering for entries with no payee

### ISSUE THREAD

**Issue by aumayr** [aumayr/beancount-web#42]
See https://github.com/aumayr/beancount-web/blob/44f322f433a9a365daf3e4e28946ff0c31a2e401/beancount_web/templates/_entry_filters.html#L116

**Comment by aumayr** [comment]
@yagebu Any idea how to implement this with the new filters?

**Comment by yagebu** [comment]
It's possible to pass the empty string along in the query string and we would have to write the frontend and backend code to handle that.

**Comment by aumayr** [comment]
I can write the frontend code, but for the backend-stuff I need help. Are you interested in implementing this feature?

**Comment by yagebu** [comment]
Took a quick look at the relevant code and since it wasn't much work, I just implemented it ;)
