### ISSUE TITLE
Unreadable graph labels when there are many

### ISSUE THREAD

**Issue by redstreet** [aumayr/beancount-web#45]
When the time span is long (in this case, 12 yearS), the labels on the horizontal axis become unreadable. See photo for example:
![bug1](https://cloud.githubusercontent.com/assets/691755/11858930/d63c7ef0-a41a-11e5-9835-81cb92db555d.png)

**Comment by aumayr** [comment]
@redstreet The new limit is a maximum of 25 labels on the x-axis. The bar-tooltips now show the date, so you don't have to guess for which timespan the bar is.

**Comment by redstreet** [comment]
@aumayr Works well now for both wide and narrow windows. :+1: for the tooltips too.
