### ISSUE TITLE
Clickable graphs [feature request]

### ISSUE THREAD

**Issue by redstreet** [aumayr/beancount-web#48]
Making graphs clickable at various points to intuitively narrow down a search would be convenient. I have no idea how easy/difficult this is, but putting it in here to see if you like the idea.

Two currently obvious places:
- with treemaps, clicking on a rectangle would apply an additional filter of the account clicked on, going to a page as if the account was clicked
- with bar graphs used in monthly plots, clicking would apply an additional filter of the month clicked on, to the existing account

**Comment by aumayr** [comment]
I created a new branch called `clickable-graphs` where I implemented three things:

- In line charts you can now zoom by dragging a rectangle over the desired zoom area
- In bar charts you now can click on individual bars to filter for that month (all bar charts show months right now)
- In tree maps the label is now better clickable and leads to the corresponding account

@redstreet Can you test the changes? Do they work for you and as you expect?

**Comment by aumayr** [comment]
Already merged into `master`.

**Comment by redstreet** [comment]
Treemaps work great! The bar and line charts work nicely too. A couple suggestions:
- line charts: works fine, but in terms of expectations, if I zoom in, I expected a time filter to be applied to the entire current view - including the table and the remaining charts. Instead, the line chart time axis gets out of sync with the table data and the remaining graphs

- bar charts: it would be nice if these were also zoomable by dragging a rectangle just like line charts. Also keeps the user experience consistent

**Comment by aumayr** [comment]
@redstreet Thanks for the feedback!

- Line charts now also set the time filter.
- Bar charts do the same. With Bar charts there is a bit of fuzziness, because the JavaScript-library `beancount-web` uses for the chart-zoom-feature does not support Bar charts natively, so I had to code it myself.

**Comment by redstreet** [comment]
One piece of feedback here: when I click to zoom or select on a bar chart or treemap, and when the page subsequently reloads with the new filter, I'm left seeing the line chart. If it's easy to put the user back on the same chart (bar or treemap) rather than return them to a line chart, it would make for a smoother experience.
