### ISSUE TITLE
Treemap colors include background color

### ISSUE THREAD

**Issue by redstreet** [aumayr/beancount-web#49]
One of the colors the treemap is currently rendering is the background color of the web page itself (white or close to it). This also happens to be the text label color. Obviously, the entire rectangle and its text disappears.

Could this color please be removed? Thanks!

**Comment by aumayr** [comment]
@redstreet Can you send/attach a small screenshot with the color you are referring to? I cannot find the near-to-white color you are mentioning in the treemap-color-definitions. Maybe with a screenshot I can track it down.

**Comment by redstreet** [comment]
I'm unfortunately unable to reproduce it using bean-example generated files.

I've attached a small portion of the right edge of the treemap, since this is a bit difficult to do without exposing a lot of private data. If it helps to know, I have about a 180 accounts in the hierarchy, and upto 5 deep. Also, if I hover over the white portions you see in the treemap, the text shown is almost the same color as the background bubble it's shown in.

Doe this help at all? If not, I'll try to reproduce this with random data later. Thanks!

![treemap-white](https://cloud.githubusercontent.com/assets/691755/11917333/d1f78dc2-a6b7-11e5-9653-6d0c331c103c.png)

**Comment by aumayr** [comment]
@redstreet This is exactly what I asked for, thanks! I will try to figure out what goes wrong here, since the white color is not part of the treemap-color-definition.

**Comment by aumayr** [comment]
@redstreet There are 15 colors for 15 different categories in a treemap. If there are more, now there is a "backup-color" that is applied to all those (which were white until now). Does that work for you?

**Comment by redstreet** [comment]
Thanks!

This certainly does solve the problem of invisible rectangles. However, where in the past, the smaller visible rectangles on the right (as shown in the screenshot I sent) had colors that matched their parents in the hierarchy, now they are all shown in gray. Meaning beyond a certain point in the treemap, all I see is gray rectangles, with no easy way to get a sense of whether they match a parent. For example, in the previous screenshot, I see a lot of magentas and blues, and immediately gain some insight from that.

Is it possible to retain the previous behavior, but only change the whites to a visible color?

**Comment by aumayr** [comment]
> Is it possible to retain the previous behavior, but only change the whites to a visible color?
> 

This is exactly what the change should have done :-/ I will look into it again, but again, could you send a small screenshot, possibly from the same account/view as before?

**Comment by redstreet** [comment]
Here it is:
![treemap](https://cloud.githubusercontent.com/assets/691755/11922475/1c9ab4c8-a74c-11e5-8925-029497909d74.png)

(Not showing the section to the left of it which is colored as before).

**Comment by aumayr** [comment]
Ahh I see the mistake, thanks for the screenshot! Will fix it in the next couple of hours.

**Comment by aumayr** [comment]
@redstreet Better? :innocent:

**Comment by redstreet** [comment]
Terrific :),  thanks much again!
![treemap](https://cloud.githubusercontent.com/assets/691755/11938990/9f4e05a0-a7d3-11e5-9840-1b60770cc809.png)
