### ISSUE TITLE
500-Error in wsgi:355 when running without --debug

### ISSUE THREAD

**Issue by corani** [aumayr/beancount-web#50]
After pulling today, I am no longer able to run `beancount-web` without `--debug`. When I do, I get an Internal Server Error (500) at `wsgi:355`.

According to `git-bisect`, this is since 838afa4a8536c1d234d6f9c3de802c361d8740c0. I suspect this may be related to #38.

When I make sure `beancount_web/static` is writable for me, the problem goes away, and I see that a `packed-general.js` file is created in `beancount_web/static/stylesheets`.

**Comment by aumayr** [comment]
This is definitely related, thanks for reporting. 

I don't know how to recreate this on my Mac - which OS are you using, @corani ?

**Comment by corani** [comment]
I'm on Linux (Ubuntu 14.04).

beancount-web is installed as `root`, so the `static/stylesheets` folder is owned as such, however, I run it as a normal user, which therefor doesn't have write access at that location.

**Comment by aumayr** [comment]
I don't know how to fix this properly, so I removed the "packaging" of JS-files altogether, serving the individual files again. This shouldn't be a performance problem, as the browser caches them anyway and they are almost certainly served locally, where speed/latency is also a non-issue.
