### ISSUE TITLE
Option to show transactions only in the account, but not children [feature-request]

### ISSUE THREAD

**Issue by redstreet** [aumayr/beancount-web#51]
beancount-web currently shows:
parent-only total: dark black
parent + children total: gray

This is very useful. However, when one clicks on the account, there is no way to see a list of the transactions for only the parent account, without also seeing the the children's transactions intermingled. It would be great to add an option to the set of options (open, close, transaction, etc.) to turn off display of transactions from children accounts, so one can see what transactions add up to the dark black number mentioned above.

**Comment by redstreet** [comment]
Nice, thanks!

When I set ````journal-show-childentries = False````, The Treemap and bar chart still seem to include children, while the line chart doesn't, if I'm seeing this right?

**Comment by aumayr** [comment]
That is correct, because if you set `journal-show-childentries = False` the treemap would only show one rectangle - the account you are viewing. Does that seem wrong/unintuitive to you?

**Comment by redstreet** [comment]
Correct, that does seem unintuitive to me. In certain cases-  in particular, when a leaf account is chosen - the treemap simply serves as a visual confirmation of the selected context rather than providing ratio information. It would be confusing if the tree map show anything else but a solid rectangular block in this case. 
  
Choosing a parent and excluding the leaves is the same situation, IMHO, and it is more important to keep the table and visual representations in sync than provide ratio data.

In my personal experience, I started doubting what the table was showing and had to go through all the transactions to determine whether or not child accounts were being shown even though I had asked for them to not be shown.
