### ISSUE TITLE
Rethink App state vs. Session state

### ISSUE THREAD

**Issue by yagebu** [aumayr/beancount-web#54]
Currently, the set of filters is saved as a global state on the `app` object. So it doesn't survive restarts of the server and makes it impractical for several users to access the same beancount-web instance. I recommend we change this to save it as a session state. I can think of two possible ways to do this:

1. "Clean URLs". Filters are sent as `POST` requests and the current filters are saved as a cookie. Flask allows us to do this easily. Quite similar to the way it is now, although I would remove the `/filter/` endpoint (except for the permalink part), as the redirect makes outputting error messages harder. (as I noticed when trying to port my dateparser exception code to master ;) )

2. Keep everything in the URL query string. Advantage would be that every URL is automatically a permalink. As we don't have to many filter options, I think it would be more transparent to use the query string to save the session state and would remove the need for a separate permalink url route.

@aumayr which option do you prefer? I have slight preference for 2., but both would be an improvement going forward.

**Comment by aumayr** [comment]
I would prefer 1., because there may be more query strings in the future (think table-column-ordering, etc.) and managing every link on every page to always have the correct query strings sounds like a huge task. 

For the "transparency"-argument in 2.: The filter-permalink shows all the selected filters in a way 2. would do, so that kind of transparency would be given in 1. as well. Do you agree?

**Comment by yagebu** [comment]
> I would prefer 1., because there may be more query strings in the future (think table-column-ordering, etc.) and managing every link on every page to always have the correct query strings sounds like a huge task.

It would only be feasible to implement 1. if we can patch `url_for` to automatically append the query string (and `app.url_defaults` looks like it does exactly that). I would reserve query strings for things like filters that massively change the data that is displayed. I think the `URL` should be a precise (as far as possible) identifier for the page that's displayed; and `/income_statement/` and `/income_statement/?time=2015` are two very different things, so they deserve unique URLs IMHO.

> For the "transparency"-argument in 2.: The filter-permalink shows all the selected filters in a way 2. would do, so that kind of transparency would be given in 1. as well. Do you agree?

Well on a website I personally couldn't be bothered with a separate link to set a bookmark. Since `beancount-web` is more of a web app, I don't mind as much; still my browser has a nice button to set a bookmark, so if there is no good reason not to have the URL be indentifying for that page, I think it's an unnecessary nuisance.

**Comment by aumayr** [comment]
>  I think the `URL` should be a precise (as far as possible) identifier for the page that's displayed;

True, and a good reason for 2. 

> still my browser has a nice button to set a bookmark, so if there is no good reason not to have the URL be indentifying for that page, I think it's an unnecessary nuisance.

Also very true, so again, looks more like 2. will be the winner after all :wink: 

> It would only be feasible to implement 1. if we can patch `url_for` to automatically append the query string
> Edit: playing around with a url_defaults function, it seems really trivial to inject the filters into every needed url. It could actually simplify the application code behind it drastically as there would be no more need for any filter_remove and connected application logic.

If this works and automatically adding the filters to `url_for` (with the possibility to add manual `GET`-parameters in the templates), then we should definitely go with the 2. option, keep everything in the URL query string.

I will create a new branch, and can you then create a PR to that branch where you show your experiments with `app.url_defaults`?

**Comment by yagebu** [comment]
> I will create a new branch, and can you then create a PR to that branch where you show your experiments with app.url_defaults?

Sounds good. My first steps are in my `filter-refactoring` branch which is a bit of a mess currently. As soon as I get it cleaned up and more complete I will submit a PR.

**Comment by aumayr** [comment]
@yagebu Are any parts missing? I tried it out extensively today and noticed no bugs.

**Comment by yagebu** [comment]
I think the `url-defaults` branch contains everything needed for this issue (and I also didn't find any more bugs) so I'll close this :)
