### ISSUE TITLE
Change Watcher works only once

### ISSUE THREAD

**Issue by corani** [aumayr/beancount-web#56]
On my system (Ubuntu 14.04), it appears the change watcher works only once. If I make one change and refresh the page, the change shows up. Subsequent changes don't show up after page refresh. 

When I restart the application, they (obviously) do show up again.

**Comment by aumayr** [comment]
@corani I cannot reproduce this behavior. Do you make the changes on the main beancount file or on an included one?

**Comment by corani** [comment]
No changes, only thing that might be different is that I'm running with `--host 0.0.0.0`, not sure if that could make a difference.

**Comment by aumayr** [comment]
On my Mac it works as expected (even with `--host 0.0.0.0`), but I will try to replicate it on an Ubuntu VM.

**Comment by aumayr** [comment]
I tried to replicate it in a fresh Ubuntu VM with Firefox, but it still works for me. @corani  Can you double check if this bug still exists in the current `HEAD `?

Please feel free to reopen this issue if it is still not working.

**Comment by corani** [comment]
I'm still seeing this issue, but I'm okay with calling it a problem on my end, until someone else can reproduce it.

**Comment by aumayr** [comment]
OK, thanks!

**Comment by aumayr** [comment]
(Accidentally put this issue number into the commits above)

**Comment by corani** [comment]
I may have figured it out. I'm using VIM, and while watching the inotify events, I see that when I save, it generates a MOVE and DELETE. No further events after that (because it doesn't automatically starts listening on the newly created file)

**Comment by aumayr** [comment]
Ahhh, now it makes sense. Thanks for investigating!

**Comment by corani** [comment]
Confirmed, if I used a different editor (nano) it works as expected.

**Comment by corani** [comment]
The easiest fix seems to be to watch the entire folder where beancount_file is located, though that might generate unnecessary reloads
