### ISSUE TITLE
Update LICENSE

### ISSUE THREAD

**Issue by aumayr** [aumayr/beancount-web#58]
- [ ] Figure out what License would be best for `beancount-web`
- [ ] Add a `LICENSE`-file
- [ ] Add a license-note to all files

**Comment by yagebu** [comment]
GPL, same as `beancount` will make moving parts into the core simpler. Don't think the fact that's it more restrictive will hurt `beancount-web`.

License note in every file is ugly and as it seems unnecessary (https://programmers.stackexchange.com/questions/125836/do-you-have-to-include-a-license-notice-with-every-source-file/125841#125841)
