### ISSUE TITLE
Keyboard shortcuts [feature request]

### ISSUE THREAD

**Issue by redstreet** [aumayr/beancount-web#65]
This is far out there, and I don't want to distract you from the terrific set of much more important features you're putting in currently, but it's an idea and I thought I'd mention it since this project is shaping up to be very well designed and very functional:

Have you considered adding keyboard shortcuts? An well designed example is gmail: if you don't already use it, then enable it in Settings, then press '?' in the main screen.

I can see keyboard shortcuts being useful for several major categories:
- navigate to one of the main pages on the left bar
- change between the handful of graph display options shown on each page
- turn on and off checkbox options (or show/hide legs) in the transactions page
- pull down the time/tag/component/payee lists on the top

**Comment by aumayr** [comment]
@redstreet Good idea! 

Can you make a concrete suggestion which shortcuts (key + function) to add?

**Comment by redstreet** [comment]
I'd be most happy to do this. I'll get back in a day or two.

**Comment by redstreet** [comment]
**Jumping to pages:**
<kbd>g</kbd> then <kbd>i</kbd>: Go to Income Statement
<kbd>g</kbd> then <kbd>b</kbd>: Go to Balance Sheet
<kbd>g</kbd> then <kbd>t</kbd>: Go to Trial Balance
<kbd>g</kbd> then <kbd>g</kbd>: Go to General Journal
<kbd>g</kbd> then <kbd>q</kbd>: Go to Custom Query

<kbd>g</kbd> then <kbd>h</kbd>: Go to Holdings
<kbd>g</kbd> then <kbd>w</kbd>: Go to Net Worth
<kbd>g</kbd> then <kbd>d</kbd>: Go to Documents
<kbd>g</kbd> then <kbd>n</kbd>: Go to Notes
<kbd>g</kbd> then <kbd>e</kbd>: Go to Events
<kbd>g</kbd> then <kbd>c</kbd>: Go to Commodities

<kbd>g</kbd> then <kbd>s</kbd>: Go to Source
<kbd>g</kbd> then <kbd>o</kbd>: Go to Options
<kbd>g</kbd> then <kbd>x</kbd>: Go to Statistics
<kbd>g</kbd> then <kbd>r</kbd>: Go to Errors

**Filtering:**
<kbd>f</kbd> then <kbd>t</kbd>: Filter by Time      ( pull down menu)
<kbd>f</kbd> then <kbd>g</kbd>: Filter by Tag       ( pull down menu)
<kbd>f</kbd> then <kbd>c</kbd>: Filter by Component ( pull down menu)
<kbd>f</kbd> then <kbd>p</kbd>: Filter by Payee     ( pull down menu)


**Options in transaction pages:**
<kbd>l</kbd>: show/hide legs
<kbd>s</kbd> then <kbd>l</kbd>: show/hide legs (duplicate shortcut for consistency)
<kbd>s</kbd> then <kbd>o</kbd>: show/hide open
<kbd>s</kbd> then <kbd>c</kbd>: show/hide close
<kbd>s</kbd> then <kbd>t</kbd>: show/hide transaction
<kbd>s</kbd> then <kbd>b</kbd>: show/hide balance
<kbd>s</kbd> then <kbd>n</kbd>: show/hide note
<kbd>s</kbd> then <kbd>d</kbd>: show/hide document
<kbd>s</kbd> then <kbd>p</kbd>: show/hide pad
<kbd>s</kbd> then <kbd>P</kbd>: show/hide padding

**General:**
<kbd>Shift</kbd> + <kbd>c</kbd>: show/hide chart
<kbd>c</kbd>: cycle through all the charts available
<kbd>/</kbd>: pull up browser's text search box (if possible?)

**Comment by aumayr** [comment]
Thanks @redstreet for the list, looks perfect!

I implemented all of them* in the `keyboard-shortcuts`-branch for you to try out. If it works for you I will merge it into master.

(* all but the last one with the browser's search box - I couldn't get it to work :/ )

**Comment by redstreet** [comment]
Works great! The <kbd>l</kbd> doesn't matter really.

One other suggestion: Is it possible to add:
<kbd>?</kbd>: show keyboard help screen overlay with list of shortcuts (like in gmail). Escape should close it

Other than that, it looks good to go!

**Comment by aumayr** [comment]
Perfect, I will merge it into master. Thanks @redstreet for the suggestions!

**Comment by corani** [comment]
I love this, thanks!
