### ISSUE TITLE
Add "Year to date" time filter [feature-request]

### ISSUE THREAD

**Issue by corani** [aumayr/beancount-web#82]
I generate my mortgage payment schedule automatically, so I have data for the next decade in my source file. This makes no sense in day-to-day reports, so I restrict the time range to "2015 - today".

It would be nice to have a predefined "Year to date" option for this in the time-filter dropdown.

**Comment by aumayr** [comment]
Should be fairly easy to add this to the suggestions in the time-filter dropdown. Are you going to try to implement this, @corani?

**Comment by corani** [comment]
Sure, I can take a stab at it. Where do you think it would fit better? In the `active_years` list, or in the `time_search_strings` search suggestions?

**Comment by aumayr** [comment]
`time_search_strings` would be better, I think.
