### ISSUE TITLE
Wrapping `beancount-web` with electron.atom.io

### ISSUE THREAD

**Issue by aumayr** [aumayr/beancount-web#89]
As an addition to the `beancount-web [filename]`-way of starting `beancount-web` I'm thinking of wrapping it with http://electron.atom.io to create a standalone-version of the  "app". 

Motivation: My girlfriend want's to use `beancount-web`, but she has no idea what a Terminal is or how to run commands/programs in it. I do not want to deploy `beancount-web` to a public webserver, as this creates costs and the `beancount`-files would be accessible online, which is not what I want. 

Is anyone else interested in this?

**Comment by aumayr** [comment]
https://www.fyears.org/2015/06/electron-as-gui-of-python-apps.html

**Comment by corani** [comment]
If you package beancount with it, and allow creation of new source files (new/open/save), you'd have a full standalone bookkeeping solution :smile:

**Comment by aumayr** [comment]
That's basically the goal :wink: 

Are you interested in this, @corani?

**Comment by corani** [comment]
It's not really something I need urgently. I'm happy building from source, and my wife can access beancount-web from the local network as-is.

However, it doesn't sound like an awful lot of work, and could be quite separate from the project as it stands. If you feel like it'll make adoption easier, by all means go for it! I'd be happy to help out where I can.

**Comment by aumayr** [comment]
The new/open/save feature is already in `beancount-web`: The editor in the Source view can open files, has Syntax highlighting, Suggestions based on Accounts opened/Currencies/Tags, and can save files to disk again. The only thing missing is the creation of new files, but the "Application" could create one on first launch, etc.

**Comment by corani** [comment]
What I meant was opening arbitrary files, not just source files supplied from the command line (or linked from that file)

**Comment by aumayr** [comment]
I moved this into it's own repository (https://github.com/aumayr/beancount-web-electron) and will contine development there.
