### ISSUE TITLE
Link for custom editor [feature request]

### ISSUE THREAD

**Issue by redstreet** [aumayr/beancount-web#92]
The built-in editor in beancount-web is a nice touch especially for small edits, but it would be great to link to a beancount:// url as shown in [1], to allow for the power of a custom editor to be opened up. I used this feature extensively with bean-web, and miss it in beancount-web. If you would consider adding this in, that would be great! Perhaps as an option in the .conf file?

https://groups.google.com/d/msg/beancount/mLa_Gdbs2xg/f50z-cdNCwAJ

**Comment by corani** [comment]
Would the following be a good solution?

Create an option (boolean): `open-source-files-externally` (this can be set using the `--settings-file` command-line argument)

If the option is set to true, the "Source" page will list the source files as beancount URI links, instead of the current dropdown + editor. Other source-links (e.g. from `errors` or `context`) will use the beancount URI scheme as well.

`beancount://<filename>?lineno=<lineno>`

**Comment by redstreet** [comment]
Sounds good! 

For clarity, I'd name the option ````open-source-files-in-external-editor ```` or simply ````use-external-editor ````.

**Comment by corani** [comment]
`use-external-editor` sounds better indeed :smile: 

I'll see if I can whip up something in a pull request.

**Comment by aumayr** [comment]
Sounds great! I already have the tooling ready to register the URL-scheme on a Mac, so I will add that as well. What is missing are scripts to register the scheme on Windows and Linux.

**Comment by redstreet** [comment]
I can add Windows and possibly Linux scripts as well once I'm able to test.

**Comment by corani** [comment]
@aumayr This issue isn't tagged as `feature` yet

**Comment by corani** [comment]
@aumayr I like the read-only view you added, but the page is getting rather long due to my large history. Is there any way to make it behave more like the internal editor? (make the links load the files asynchronously)

**Comment by aumayr** [comment]
@corani Yes, I can add that.

**Comment by redstreet** [comment]
````use-external-editor```` works great, thank you!

I am ready to add the Windows portion of registering the beancount:// URI.  This consists of two files: a .reg registry file, and a .bat batch file. If @aumayr or @corani could please suggest a good location in the source tree to place them, I'll submit a pull request. Thanks again!

**Comment by aumayr** [comment]
@redstreet sure: 

- First create a `windows` and `linux` directory in `beancount_urlscheme` and place any scripts (except python), binaries or executables that you need in there (as I did in the `mac` directory). 
- Then extend the `register` command to include the newly supported platforms here: https://github.com/aumayr/beancount-web/blob/master/beancount_urlscheme/beancount_urlscheme.py#L41-L53
- Lastly, the helper-scripts/-executables that then handle the `beancount://`-URL-scheme should call `beancount-urlscheme --line LINE FILENAME` when such a URL is opened.

**Comment by aumayr** [comment]
> @aumayr I like the read-only view you added, but the page is getting rather long due to my large history. Is there any way to make it behave more like the internal editor? (make the links load the files asynchronously)

@corani Done: cf223295afd135c552aa27e4187278c31689b37e

**Comment by corani** [comment]
Awesome, thanks!

**Comment by redstreet** [comment]
Thanks @aumayr . Submitted pull request #95. Unfortunately, it's not easy to use the existing beancount_urlscheme.py in cygwin, because of the following limitations:
1) Windows registry install needs to be called as admin, and I can't seem to find a way to execute thsi from within Cygwin
2) Using beancount_urlscheme.py each time a user clicks on the web would not work well in Cygwin because it's not easy to call Cygwin's python install (as opposed to the native Windows python install, if one exists) from the registry handler. This would probably involve going through Cygwin's run.exe, and this is fraught with too many problems. It's much more simpler and elegant in this case, to simply call the editor of one's choice

So I've documented this in beancount_urlscheme.py in addition to providing the .bat and .reg files.

**Comment by aumayr** [comment]
Thanks, @redstreet! Although it is not entirely userfriendly, I can understand the hassle!
